export const SET_LISTING = "SET_LISTING";
export const SET_AUCTION = "SET_AUCTION";
export const SET_STEP = "SET_STEP";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const UPDATE_USER_PROFILE_IMAGE = "UPDATE_USER_PROFILE_IMAGE";
